name: DeathBan
version: ${version}
main: dev.t0g3pii.deathban.NilsAngDeathBanPlugin
api-version: '1.21'
authors: ["t0g3pii"]
softdepend: ["PlaceholderAPI", "AdvancedBan", "DiscordSRV"]
commands:
  deathban:
    description: Verwaltung für DeathBan
    usage: /deathban <reload|unban|remaining|list|listmods|modunban> [spieler]
permissions:
  deathban.exempt:
    description: Spieler mit dieser Permission sind nicht vom DeathBan betroffen
    default: false
  deathban.moderator:
    description: Moderatoren werden statt gebannt in den Spectator versetzt
    default: false
  deathban.streamer:
    description: Streamer-Flow (wie Moderator) plus einmaliger Kick nach dem Tod
    default: false
  deathban.admin:
    description: Adminrechte für Reload/Unban/Abfragen
    default: op
